### ISSUE TITLE
.pom file uploaded for 1.7.1?

### ISSUE THREAD

**Issue by lmarthorburn** [jenkinsci/checks-api-plugin#117]
I that there's a .pom file uploaded for a version 1.7.1 but nothing else:
https://repo.jenkins-ci.org/releases/io/jenkins/plugins/checks-api/1.7.1/
And 1.7.0 is the latest release. What is the status of 1.7.1 and why has this .pom file been uploaded?
Best regards,
Lavina

**Comment by XiongKezhi** [comment]
Failed to release 1.7.1 due to some problem. Now I released https://repo.jenkins-ci.org/ui/native/releases/io/jenkins/plugins/checks-api/1.7.2/ since we don't allow for replacing the existing releases.
