### ISSUE TITLE
Phantom release 1.7.5 of checks-api

### ISSUE THREAD

**Issue by dja-fr** [jenkinsci/checks-api-plugin#184]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  junit:1119.1121.vc43d0fc45561
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins LTS 2.346.x 

### Reproduction steps

1. jenkins-plugin-cli --no-download --verbose --plugins junit:1119.1121.vc43d0fc45561

Installed version (1.7.4) of checks-api is less than minimum required version of 1.7.5, bundled plugin will be upgraded

### Expected Results

Use last available checks-api plugin version aka : 1.7.4

### Actual Results

Try to use version 1.7.5 ( 404 not found)

### Anything else?

No

**Comment by timja** [comment]
see https://github.com/jenkins-infra/helpdesk/issues/3095#issuecomment-1211697808

please report infra issues on helpdesk, nothing to do with checks-api plugin itself
