### ISSUE TITLE
[Question] Hanging checks with "withChecks()"

### ISSUE THREAD

**Issue by noru** [jenkinsci/checks-api-plugin#199]
Hi, 

I'm using Checks API plugin along with Github Checks API. According to the document, I wrote this code in my pipeline script:
 
```groovy
steps {
    withChecks('CI/Main/CheckStyle') {
        // do stuff
        exit 1 // if error occured, the check will be completed with error  
         
        // But if everything is fine, no "COMPLETED" is published to the check, leave it forever hanging.
        // to solve this I'll have to manually do a publish 
        echo 'hello'
        publishChecks(name: 'CI/Main/CheckStyle', conclusion: 'SUCCESS', summary: 'Lint passed')
    }
}
```

The check is successfully published, but, as described above, I'll have to manually complete a check  in my steps.

It seems the code [didn't publish any checks in `onSuccess`](https://github.com/jenkinsci/checks-api-plugin/blob/master/src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java#L209) on purpose. 

I googled a lot for the usage of `withChecks`, no mention of this behavior. And examples on Github simply wrap normal steps without the manual complete.

I'm new to this, my usage could be wrong. Could someone help me with the correct usage of `witchChecks`? Appreciated!

**Comment by noru** [comment]
Thanks @KalleOlaviNiemitalo ! That explains it.

Though this should be documented properly I think.

**Comment by mrginglymus** [comment]
The pattern I'd always intended to use with this (but never got round to implementing) was to add an optional checks publisher to `warnError`. For e.g. running tests you can do:

```groovy
withChecks('My Tests') {
    sh 'run_tests > results.xml'
    junit 'results.xml'
}
```
and that works fine; sometimes you have a one-shot command where you just want to report success or failure. It would be nice to extend `warnError` to be checks aware:

```groovy
withChecks('One Shot') {
    warnError('One Shot') {
        sh 'one_shot'
    }
}
```
ie, have warnError report the appropriate success/failure message to the active checks context. 

Alternatively get `warnError` to be fully responsible for doing the checks itself, so
```groovy
warnError(message: 'One Shot', publishChecks: true) {
    sh 'one_shot'
}
```

Not sure why I never got round to doing it, but happy to take another look if people think it might be a useful pattern?

**Comment by timja** [comment]
created https://github.com/jenkinsci/checks-api-plugin/issues/200 to track enhancement

**Comment by timja** [comment]
Semi related pull request which helps in some cases: https://github.com/jenkinsci/checks-api-plugin/pull/254
