### ISSUE TITLE
2.2.1 Release Information Missing

### ISSUE THREAD

**Issue by davmillar** [jenkinsci/checks-api-plugin#264]
### Describe your use-case which is not covered by existing documentation.

My Jenkins instance is reporting version 2.2.1 available, but the latest release in GitHub is 2.2.0. I am interested in seeing the changelog for 2.2.1 from 2.2.0 before applying the update.

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

https://plugins.jenkins.io/checks-api/releases/#version_2.2.0

### Are you interested in contributing to the documentation?

I'm not familiar with doing this but open to trying.

**Comment by timja** [comment]
Apologies this plugin isn't using automated release right now and I forgot about the manual step to publish release notes, its done now
