### ISSUE TITLE
Expose annotations to the publishChecks step

### ISSUE THREAD

**Issue by jammer87** [jenkinsci/checks-api-plugin#28]
Add the ability to include annotations using the publishChecks step.

Here's the use case in a scripted pipeline, but in practice I would use a previously generated file for readJSON rather than text.

```groovy
List issues = []
readJSON(text: '''[
    {
        'path': 'src/main/java/io/jenkins/plugins/checks/api/ChecksAnnotation.java', 
        'startLine': 5, 
        'endLine': 6, 
        'annotationLevel': 'NOTICE', 
        'message': 'you did something wrong', 
        'startColumn': 4, 
        'endColumn': 7, 
        'title': 'Bad thing', 
        'rawDetails': 'you did this specific thing wrong and you should fix it'
    }
]''').each {issue->
    issues.add(checksAnnotation(issue))  //checksAnnotation method would build and return a ChecksAnnotation object
}

publishChecks name: 'Check', title: 'Title', summary: 'Summary', text: 'Details', annotations: issues
```

Similar functionality for images and actions may be useful as well.

**Comment by uhafner** [comment]
As a workaround you can parse such files with the warnings plugin. Then you get the checks for free...

**Comment by jammer87** [comment]
> As a workaround you can parse such files with the warnings plugin. Then you get the checks for free...

I had considered using the warnings plugin, but that only includes new issues as annotations. The annotations disappear if you run the job again and the issue still exists. I want anything in this file to be an annotation, regardless of the results of previous runs.

This plugin is fantastic! The existing functionality has been very beneficial for my team after only a week of using it.

**Comment by uhafner** [comment]
It might be worth to create a feature request for a toggle in the warnings plugin.

**Comment by uhafner** [comment]
BTW: I added an [option to render all warnings](https://github.com/jenkinsci/warnings-ng-plugin/pull/724) in the warnings plugin. It is available in the latest release now.
