### ISSUE TITLE
[Checks API] No suitable checks publisher found.

### ISSUE THREAD

**Issue by houseofyin** [jenkinsci/checks-api-plugin#32]
Folks,

I am migrating to a new Jenkins instance.  The previous one did not have the Checks API plugin installed, but the new one does.

I have a a job that is failing with the following error message:

Commit message: "Merge pull request #105 in ADS/itt from ibp-prod-updates to master"
Posting build status of INPROGRESS to NHLBI Bitbucket for commit id [db3c75841c2d6aef50cf95622890715a1c776234] and ref 'null'
[Checks API] No suitable checks publisher found

The pipeline never gets past the Declarative: Check, out SCM step.  I don't think it is successfully completing the pull from git, so I don't think the job is even seeing the Jenkinsfile.  The [Checks API] error is the last thing I see in the log before it goes to the Declarative: Post Actions, and the only obvious error in the log, so I figured I would start here to see there were any suggestions.

Thanks!

**Comment by litan1106** [comment]
> Folks,
> 
> I am migrating to a new Jenkins instance. The previous one did not have the Checks API plugin installed, but the new one does.
> 
> I have a a job that is failing with the following error message:
> 
> Commit message: "Merge pull request #105 in ADS/itt from ibp-prod-updates to master"
> Posting build status of INPROGRESS to NHLBI Bitbucket for commit id [db3c75841c2d6aef50cf95622890715a1c776234] and ref 'null'
> [Checks API] No suitable checks publisher found
> 
> The pipeline never gets past the Declarative: Check, out SCM step. I don't think it is successfully completing the pull from git, so I don't think the job is even seeing the Jenkinsfile. The [Checks API] error is the last thing I see in the log before it goes to the Declarative: Post Actions, and the only obvious error in the log, so I figured I would start here to see there were any suggestions.
> 
> Thanks!

Did you setup the project with Github App credential? The Check API plugin won't work with ssh credential.

```
The recommended git tool is: NONE
using credential github-app-XXX
Cloning the remote Git repository
Cloning repository https://github.com/XXX
```

**Comment by houseofyin** [comment]
Folks,

We are using an on premises instance of BitBucket, not Github.

**Comment by allout58** [comment]
I'm not sure if there is a plugin for BitBucket yet. In order for this plugin to work, you also have to install an implementation plugin as well, such as the [Github Checks Plugin](https://plugins.jenkins.io/github-checks)

**Comment by XiongKezhi** [comment]
> Folks,
> 
> We are using an on premises instance of BitBucket, not Github.

Sorry, we haven't provided the implementation for BitBucket yet. Is there any similar API in bitbucket? If so, I think we can provide an implementation for it in the future.

**Comment by houseofyin** [comment]
I'm a bit puzzled about the behavior I am seeing though.

* In the job that is failing, the failure happens right after the checkout, but before Jenkins is able to process the pipeline.  The pipeline of the job with the problem doesn't have any apparent direct or direct references to the Checks API.   
* I have another job that is working, and it appears to use the Checks API.  ( It users the Warnings and the Cobertura plugins, which have Checks API as an upstream dependency )

Both jobs are for projects in BitBucket repositories, and are pulled into Jenkins using the Bitbucket Server Integration plugin.

I am not trying to publish results to BitBucket in either case.

**Comment by timja** [comment]
I highly doubt this plugin has anything to do with it,

It's just a log message for information

**Comment by houseofyin** [comment]
You are correct.  It turns out something else was failing silently right after that message.  Thanks for your help.
