### ISSUE TITLE
Add a `LogPublisher` for test.

### ISSUE THREAD

**Issue by XiongKezhi** [jenkinsci/checks-api-plugin#54]
Currently, we don't have a reliable way to test the features (e.g. status checks, checks steps) that require the involvement of an implementation. Thus, adding a `LogPublisher` only for testing that logs the check details or anything being published is a good way to improve our test coverage and quality.

After injecting the `LogPublisher` into the Jenkins instance while testing, we can later check the log to make assertions, examples are like: https://github.com/jenkinsci/checks-api-plugin/blob/75b92fb04b1de582226553691c27b6a6dff1531c/src/test/java/io/jenkins/plugins/checks/steps/PublishChecksStepITest.java#L28

**Comment by mrginglymus** [comment]
For the junit plugin I created a publisher that just stores published checks in a simple list:

https://github.com/jenkinsci/junit-plugin/blob/master/src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java#L35-L66

that can be inspected after a run has finished.

Might this be something useful to move into here?
