### ISSUE TITLE
Cannot build plugin

### ISSUE THREAD

**Issue by mrginglymus** [jenkinsci/checks-api-plugin#56]
Since the addition of the `withChecks` (#49), I've been unable to build locally, due to the error:

```
 Failed to resolve new artifacts: Could not find artifact io.jenkins.plugins:checks-api:hpi:1.2.0null in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/). The API analysis will not proceed.
```

Adding back the `-SNAPSHOT` to the pom doesn't help, as it then complains about breaking semantic versioning.

Out of interest, I tried bumping to `2.0.0` (with `-SNAPSHOT`), which succeeded, but with:

```
Failed to resolve old artifacts: Could not find artifact io.jenkins.plugins:checks-api:hpi:1.2.0${changelist} in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/). The API analysis will proceed comparing the new archives against an empty archive.
```

:(

**Comment by uhafner** [comment]
This is what I noted in my review: https://github.com/jenkinsci/checks-api-plugin/pull/49/files#r544681526

**Comment by uhafner** [comment]
Without a SNAPSHOT we cannot release as well.
