### ISSUE TITLE
publishChecks step: the conclusion should be none when status is not completed

### ISSUE THREAD

**Issue by XiongKezhi** [jenkinsci/checks-api-plugin#72]
Currently, the `publishChecks` step has a default `success` value for the conclusion, however, it should reset the conclusion to be `none` when the status is `queued` or `in_progress`. Otherwise, users may have to explicitly set the conclusion to be `none` since, like GitHub, it will automatically set the status to be `completed` when `conclusion` is provided.

See the context: https://github.com/jenkinsci/checks-api-plugin/issues/70#issuecomment-765606154

**Comment by ThusithaDJ** [comment]
Hi @XiongKezhi, If this fix is not super urgent, can I work on this?

**Comment by XiongKezhi** [comment]
go ahead! thanks!

**Comment by ThusithaDJ** [comment]
@XiongKezhi, is this issue fixed, or am I checking at the wrong place?
https://github.com/jenkinsci/checks-api-plugin/blob/64dc0a6c55c704c1d716d5532ed16cce9358584c/src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java#L128-L129

https://github.com/jenkinsci/checks-api-plugin/blob/64dc0a6c55c704c1d716d5532ed16cce9358584c/src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java#L152-L153

**Comment by KalleOlaviNiemitalo** [comment]
BuildStatusChecksPublisher is the wrong place. You need [PublishChecksStep](https://github.com/jenkinsci/checks-api-plugin/blob/64dc0a6c55c704c1d716d5532ed16cce9358584c/src/main/java/io/jenkins/plugins/checks/steps/PublishChecksStep.java).

**Comment by ThusithaDJ** [comment]
Thanks, @KalleOlaviNiemitalo. To be clear, I shouldn't change the `conclusion` variable's default value but need to add a condition to check whether `status` is `queued` or `in_progress`, right?

**Comment by KalleOlaviNiemitalo** [comment]
I don't really know what is the best way to implement this. Anyway, please test that the pipeline snippet generator behaves in a sensible way after your changes.

**Comment by XiongKezhi** [comment]
> Thanks, @KalleOlaviNiemitalo. To be clear, I shouldn't change the `conclusion` variable's default value but need to add a condition to check whether `status` is `queued` or `in_progress`, right?

yes, you should add a condition to check the status when setting the conclusion.

**Comment by ThusithaDJ** [comment]
Ok sure. Thanks a lot, both of you.

**Comment by ThusithaDJ** [comment]
@XiongKezhi, could you please let me know if you have any guide to follow on setting up the plugin for local testing? I referred to the [Consumers Guide](https://github.com/jenkinsci/checks-api-plugin/blob/master/docs/consumers-guide.md) and [Implementation Guide](https://github.com/jenkinsci/checks-api-plugin/blob/master/docs/implementation-guide.md), but it's a bit unclear for me. It would be better if you can help me with this.

**Comment by XiongKezhi** [comment]
Sorry, those are not guides for users, they are for other plugin developers. 

So when you are trying to test this plugin locally, first you need to set up a Jenkins instance for remote debugging. If you are using a Jenkins war file, startup it with the java options like (for more, see [here](https://wiki.jenkins.io/display/JENKINS//Starting+and+Accessing+Jenkins)):
```
-Xdebug -Xrunjdwp:transport=dt_socket,address=127.0.0.1:8000,server=y,suspend=n
```
Then you can set up your remote debugger to attach to it.


Finally, you need a Jenkins project to run the code of this plugin:
1. Set up the GitHub app credentials as in this [guide](https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc)
2. Use the GitHub app credentials you added to Jenkins in the last step in one of your projects. I have a multi-branch project set up like this (you should use the repository that your GitHub app is installed on):

<img width="944" alt="截屏2021-02-09 上午12 10 53" src="https://user-images.githubusercontent.com/30348893/107246510-495feb80-6a6b-11eb-8f9a-443955f23da4.png">

And since you are going to modify the `publishChecks` step, so you should have a repository with a Jenkins pipeline calling `publishChecks`.

**Comment by timja** [comment]
personally I just change the dependency in the github checks repo to a SNAPSHOT dependency, build this project with `mvn install -P quick-build` and then run the github checks project with `mvn hpi:run` using the debug option in my IDE

or just using unit tests for some changes where I don't actually need GitHub

**Comment by ThusithaDJ** [comment]
Hi @XiongKezhi, I have pushed some changes, please check that and let me know your thoughts. 
https://github.com/jenkinsci/checks-api-plugin/pull/82

**Comment by XiongKezhi** [comment]
fixed by https://github.com/jenkinsci/checks-api-plugin/pull/82
