### ISSUE TITLE
Rendering issues with pipeline information in 'Jenkins' check

### ISSUE THREAD

**Issue by timja** [jenkinsci/checks-api-plugin#79]
e.g.

https://github.com/jenkinsci/google-oauth-plugin/runs/1864403011

I think multiple failures breaks it, I've seen it in a couple of places

![image](https://user-images.githubusercontent.com/21194782/107391197-5d99fc00-6af0-11eb-917c-cd0d79d6daa9.png)

fyi @mrginglymus

**Comment by mrginglymus** [comment]
Error: null doesn’t look great either!

**Comment by mrginglymus** [comment]
### `Potato`
potato in `potato` step, with arguments potato
```
potato
```
<details>
<summary>Potato</summary>
```
Hello
```
</details>
### `Potato`
potato in `potato` step, with arguments potato
```
potato
```
<details>
<summary>Potato</summary>
```
Hello
```
</details>

---

looks like we need to throw newlines at the problem
