### ISSUE TITLE
Local build doesn't fail for checkstyle or spotbugs

### ISSUE THREAD

**Issue by timja** [jenkinsci/checks-api-plugin#99]
Pretty frustrating, what is your workflow for this @uhafer?

I run `mvn clean install` and then I create a PR and it fails for spotbugs or checkstyle

**Comment by uhafner** [comment]
I normally never use maven locally 😄 

I commit (and IntelliJ starts CheckStyle and SpotBugs Issues before the commit). That is typically enough for me. The problem with maven is that it cannot check for new issues.

**Comment by timja** [comment]
Do you have a pre commit hook that runs them?

i.e how do you have it setup to run those?

**Comment by uhafner** [comment]
I'm just using the checkstyle and spotbugs plugins:

![Bildschirmfoto 2021-04-01 um 20 18 28](https://user-images.githubusercontent.com/503338/113337084-9489d280-9327-11eb-9a5f-e0771c8f1d99.png)

**Comment by basil** [comment]
> The problem with maven is that it cannot check for new issues.

There is at least some precedent for ratcheting functionality in [Spotless Maven Plugin](https://github.com/diffplug/spotless/tree/main/plugin-maven#how-can-i-enforce-formatting-gradually-aka-ratchet=).
